---
- name: 部署alacritty
  hosts: ubuntu_22
  become: yes
  vars:
    current_user: "{{ ansible_ssh_user | default(lookup('env', 'USER'), true) }}"
    current_pass: "{{ ansible_ssh_pass | default(lookup('env', 'USER'), true) }}"
    current_become_pass: "{{ ansible_become_pass | default(lookup('env', 'USER'), true) }}"
    current_user_home: "{{ ansible_ssh_user_home | default(lookup('env', 'HOME'), true) }}"
  any_errors_fatal: true
  tasks:
    - name: 添加仓库
      ansible.builtin.command:
        cmd: add-apt-repository ppa:aslatter/ppa -y # sudo add-apt-repository ppa:mmstick76/alacritty
      environment:
        https_proxy: "{{ clash_proxy_url }}:{{ clash_proxy_port }}"
        http_proxy: "{{ clash_proxy_url }}:{{ clash_proxy_port }}"
      when: true

    - name: 卸载旧的alacritty
      apt:
        name:
          - alacritty
        state: absent

    - name: 删除残留的alacritty
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ current_user_home }}/.config/alacritty"

    - name: 更新软件源包列表
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: 安装alacritty
      apt:
        name:
          - alacritty
        state: present
      environment: # 处理连接不上仓库的问题
        https_proxy: "{{ clash_proxy_url }}:{{ clash_proxy_port }}"
        http_proxy: "{{ clash_proxy_url }}:{{ clash_proxy_port }}"

    - name: 删除仓库 # 避免 apt update 失败
      ansible.builtin.command:
        cmd: add-apt-repository --remove ppa:aslatter/ppa -y
      environment:
        https_proxy: "{{ clash_proxy_url }}:{{ clash_proxy_port }}"
        http_proxy: "{{ clash_proxy_url }}:{{ clash_proxy_port }}"
      when: true

    - name: 下载alacritty的配置
      include_tasks: util_git_clone.yml
      vars:
        git_repo_url: "https://github.com/gvls/alacritty.git"
        git_repo_dir: "{{ current_user_home }}/.config/alacritty"


