---
- name: 部署chatbox
  hosts: ubuntu_22
  become: yes
  vars:
    current_user: "{{ ansible_ssh_user | default(lookup('env', 'USER'), true) }}"
    current_pass: "{{ ansible_ssh_pass | default(lookup('env', 'USER'), true) }}"
    current_become_pass: "{{ ansible_become_pass | default(lookup('env', 'USER'), true) }}"
    current_user_home: "{{ ansible_ssh_user_home | default(lookup('env', 'HOME'), true) }}"
  any_errors_fatal: true
  tasks:
    - name: 删除残留的chatbox
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/opt/script/bin/chatbox.AppImage"

    - name: 安装依赖
      apt:
        name:
          - libfuse-dev
        state: present

    - name: 下载chatbox
      get_url:
        url: "{{ chatbox_bin_url }}"
        dest: "/opt/script/bin/chatbox.AppImage"
        mode: '0775'
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
      # become_user: "{{ current_user }}"
