---
- name: 部署cursor
  hosts: ubuntu_22
  become: yes
  vars:
    current_user: "{{ ansible_ssh_user | default(lookup('env', 'USER'), true) }}"
    current_pass: "{{ ansible_ssh_pass | default(lookup('env', 'USER'), true) }}"
    current_become_pass: "{{ ansible_become_pass | default(lookup('env', 'USER'), true) }}"
    current_user_home: "{{ ansible_ssh_user_home | default(lookup('env', 'HOME'), true) }}"
  any_errors_fatal: true
  tasks:
    - name: 删除残留的cursor
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/opt/script/bin/cursor.AppImage"

    - name: 下载cursor
      get_url:
        url: "{{ cursor_bin_url }}"
        dest: "/opt/script/bin/cursor.AppImage"
        mode: '0775'
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
      # become_user: "{{ current_user }}"

    - name: 配置cursor配置
      copy:
        src: ./pkg/cursor.code-profile
        dest: "{{ current_user_home }}/Downloads/cursor.code-profile"
        force: yes
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
        mode: "664"
      become_user: "{{ current_user }}"
