---
- name: 部署drawio
  hosts: ubuntu_22
  become: yes
  vars:
    current_user: "{{ ansible_ssh_user | default(lookup('env', 'USER'), true) }}"
    current_pass: "{{ ansible_ssh_pass | default(lookup('env', 'USER'), true) }}"
    current_become_pass: "{{ ansible_become_pass | default(lookup('env', 'USER'), true) }}"
    current_user_home: "{{ ansible_ssh_user_home | default(lookup('env', 'HOME'), true) }}"
  any_errors_fatal: true
  tasks:
    - name: 删除残留的drawio
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/opt/script/bin/drawio.AppImage"

    - name: 下载drawio
      include_tasks: util_wget_proxy.yml
      vars:
        wget_url: "{{ drawio_bin_url }}"
        wget_dir: "/opt/script/bin/drawio.AppImage"

