---
- name: 部署etcd
  hosts: ubuntu_22
  become: yes
  vars:
    current_user: "{{ ansible_ssh_user | default(lookup('env', 'USER'), true) }}"
    current_pass: "{{ ansible_ssh_pass | default(lookup('env', 'USER'), true) }}"
    current_become_pass: "{{ ansible_become_pass | default(lookup('env', 'USER'), true) }}"
    current_user_home: "{{ ansible_ssh_user_home | default(lookup('env', 'HOME'), true) }}"
  any_errors_fatal: true
  tasks:
    - name: 更新软件源包列表
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: 安装etcd
      apt:
        name:
          - etcd
        state: present

    - name: 配置etcd
      blockinfile:
        path: "{{ current_user_home }}/.bashrc"
        block: |
          export ETCDCTL_API=3
        marker: "# {mark} etcd BLOCK"
        create: yes
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
      become_user: "{{ current_user }}"
