---
- name: 部署firefox
  hosts: ubuntu_22
  become: yes
  vars:
    current_user: "{{ ansible_ssh_user | default(lookup('env', 'USER'), true) }}"
    current_pass: "{{ ansible_ssh_pass | default(lookup('env', 'USER'), true) }}"
    current_become_pass: "{{ ansible_become_pass | default(lookup('env', 'USER'), true) }}"
    current_user_home: "{{ ansible_ssh_user_home | default(lookup('env', 'HOME'), true) }}"
  any_errors_fatal: true
  tasks:
    # - name: 写入需要手动操作的信息
    #   template:
    #     src: ./pkg/firefox.md
    #     dest: "{{ current_user_home }}/TODO_firefox.md"
    #     owner: "{{ current_user }}"
    #     group: "{{ current_user }}"
    #     mode: "664"
    #   become_user: "{{ current_user }}"

    - name: 设置snap代理
      command:
        cmd: "/usr/bin/snap set system proxy.http='http://127.0.0.1:7890'"

    - name: 设置snap https代理
      command:
        cmd: "/usr/bin/snap set system proxy.https='http://127.0.0.1:7890'"

    - name: 查看snap代理配置
      command:
        cmd: "/usr/bin/snap get system proxy"

    - name: 更新firefox
      command:
        cmd: "/usr/bin/snap refresh firefox"
      register: command_result
      until: command_result.failed == false
      retries: 3
      delay: 3

    # sudo snap unset system proxy

    - name: 清除snap代理
      command:
        cmd: "/usr/bin/snap set system proxy.http=''"

    - name: 清除snap https代理
      command:
        cmd: "/usr/bin/snap set system proxy.https=''"

    - name: 查看snap代理配置
      command:
        cmd: "/usr/bin/snap get system proxy"
