---
- name: 部署fzf
  hosts: ubuntu_22
  become: yes
  vars:
    current_user: "{{ ansible_ssh_user | default(lookup('env', 'USER'), true) }}"
    current_pass: "{{ ansible_ssh_pass | default(lookup('env', 'USER'), true) }}"
    current_become_pass: "{{ ansible_become_pass | default(lookup('env', 'USER'), true) }}"
    current_user_home: "{{ ansible_ssh_user_home | default(lookup('env', 'HOME'), true) }}"
  any_errors_fatal: true
  tasks:
    - name: 更新软件源包列表
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: 安装fzf
      apt:
        name:
          - fzf
          - bat # 预览用
        state: present

    - name: 配置fzf
      blockinfile:
        path: "{{ current_user_home }}/.bashrc"
        block: |
            export FZF_DEFAULT_OPTS='--color=fg+:44,hl:124,hl+:196' # hl hl+ fg fg+ bg bg+
            #export FZF_DEFAULT_OPTS="--height 97% --border --preview 'batcat --color=always {}'"
            #export FZF_DEFAULT_OPTS='--bind ctrl-e:down,ctrl-u:up --preview \"[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | he  ad -500\"'
            # install the_silver_searcher
            #export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
            #export FZF_COMPLETION_TRIGGER='\\'
            #export FZF_PREVIEW_COMMAND='[[file --mime {} =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500'
            #export FZF_CTRL_T_COMMAND="ctrl-f"
        marker: "# {mark} fzf BLOCK"
        create: yes
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
      become_user: "{{ current_user }}"
