---
- name: 部署fzf
  hosts: ubuntu_22
  become: yes
  any_errors_fatal: true
  tasks:
    - name: 更新软件源包列表
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: 安装fzf
      apt:
        name:
          - fzf
          - bat # 预览用
        state: present

    - name: 配置fzf
      blockinfile:
        path: "{{ ansible_ssh_user_home }}/.bashrc"
        block: |
            #export FZF_DEFAULT_OPTS='--bind ctrl-e:down,ctrl-u:up --preview \"[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | he  ad -500\"'
            # install the_silver_searcher
            #export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
            #export FZF_COMPLETION_TRIGGER='\\'
            #export FZF_PREVIEW_COMMAND='[[file --mime {} =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500'
            #export FZF_DEFAULT_OPTS="--height 97% --border --preview 'cat {}'"
            export FZF_DEFAULT_OPTS="--height 97% --border --preview 'batcat {}'"
            #export FZF_CTRL_T_COMMAND="ctrl-f"
        marker: "# {mark} fzf BLOCK"
        create: yes
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
      become_user: "{{ ansible_ssh_user }}"
