---
- name: 部署goland
  hosts: ubuntu_22
  become: yes
  vars:
    current_user: "{{ ansible_ssh_user | default(lookup('env', 'USER'), true) }}"
    current_pass: "{{ ansible_ssh_pass | default(lookup('env', 'USER'), true) }}"
    current_become_pass: "{{ ansible_become_pass | default(lookup('env', 'USER'), true) }}"
    current_user_home: "{{ ansible_ssh_user_home | default(lookup('env', 'HOME'), true) }}"
  any_errors_fatal: true
  tasks:
    - name: 删除残留的goland
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/goland.deb"

    - name: 下载goland
      get_url:
        url: "{{ goland_deb_url }}"
        dest: "/tmp/goland.deb"
        mode: '0664'
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
      become_user: "{{ current_user }}"


    - name: 安装goland
      ansible.builtin.apt:
        deb: "/tmp/goland.deb"


