- name: 部署lazygit
  hosts: ubuntu_22
  become: yes
  vars:
    current_user: "{{ ansible_ssh_user | default(lookup('env', 'USER'), true) }}"
    current_pass: "{{ ansible_ssh_pass | default(lookup('env', 'USER'), true) }}"
    current_become_pass: "{{ ansible_become_pass | default(lookup('env', 'USER'), true) }}"
    current_user_home: "{{ ansible_ssh_user_home | default(lookup('env', 'HOME'), true) }}"
  any_errors_fatal: true
  tasks:
    - name: 安装lazygit
      include_tasks: util_go_install.yml
      loop:
        - "github.com/jesseduffield/lazygit@v0.40.2"
      loop_control:
        loop_var: "go_project"

    - name: 创建lazygit配置目录
      ansible.builtin.file:
        path: "{{ current_user_home }}/.config/lazygit"
        state: directory
        mode: '0755'
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
      become_user: "{{ current_user }}"

    - name: 配置lazygit配置
      copy:
        src: ./pkg/lazygit.yml
        dest: "{{ current_user_home }}/.config/lazygit/config.yml"
        force: yes
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
        mode: "664"
      become_user: "{{ current_user }}"

    - name: 配置lazygit别名
      blockinfile:
        path: "{{ current_user_home }}/.bashrc"
        block: |
          alias lg='lazygit'
        marker: "# {mark} lazygit BLOCK"
        create: yes
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
      become_user: "{{ current_user }}"

    - name: 下载glab
      include_tasks: util_git_clone.yml
      vars:
        git_repo_url: "https://github.com/profclems/glab.git"
        git_repo_dir: "/tmp/glab"

    - name: 编译glab
      command:
        cmd: "/usr/bin/make"
        chdir: "/tmp/glab"
        #become_user: "{{ current_user }}" # 不能使用这个
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
        GOPATH: "/opt/go"
        GOPROXY: "https://goproxy.cn,direct"
        HTTPS_PROXY: "{{ clash_proxy_url }}:{{ clash_proxy_port }}"

    - name: 安装glab运行工具
      command:
        cmd: "cp -f /tmp/glab/bin/glab /opt/go/bin"

    - name: 创建glab-cli配置目录
      ansible.builtin.file:
        path: "{{ current_user_home }}/.config/glab-cli"
        state: directory
        mode: '0755'  # 设置目录权限，根据需要调整
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
      become_user: "{{ current_user }}"

    - name: 创建glab-cli数据文件
      ansible.builtin.file:
        path: "{{ current_user_home }}/.config/glab-cli/branch.txt"
        state: touch
        mode: '0644'  # 设置文件权限，根据需要调整
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
      become_user: "{{ current_user }}"
