---
- name: 部署nodejs
  hosts: ubuntu_22
  become: yes
  any_errors_fatal: true
  tasks:
    - name: 卸载旧的nodejs、npm
      apt:
        name:
          - nodejs
          - npm
        state: absent

    - name: 删除残留的nodejs和npm
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/usr/bin/npm"
        - "/usr/local/bin/npm"
        - "/usr/bin/node"
        - "/usr/bin/nodejs"
        - "/usr/local/bin/node"
        - "/usr/local/bin/nodejs"

    - name: 更新软件源包列表
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: 安装nodejs、npm
      apt:
        name:
          - nodejs # v12.22.9
          - npm # 8.19.2
        state: present

    - name: npm清理缓存
      command:
        cmd: "/usr/bin/npm cache clear --force"
        chdir: "{{ ansible_ssh_user_home }}"
      become_user: "{{ ansible_ssh_user }}"

    - name: npm设置仓库
      command:
        cmd: "/usr/bin/npm config set registry {{ nodejs_warehouse }}"
        chdir: "{{ ansible_ssh_user_home }}"
      become_user: "{{ ansible_ssh_user }}"

        #- name: npm设置http代理
        #  command:
        #    cmd: "/usr/bin/npm config set proxy {{ clash_proxy_url }}:{{ clash_proxy_port }}"
        #    chdir: "{{ ansible_ssh_user_home }}"
        #  become_user: "{{ ansible_ssh_user }}"

        #- name: npm设置https代理
        #  command:
        #    cmd: "/usr/bin/npm config set https-proxy {{ clash_proxy_url }}:{{ clash_proxy_port }}"
        #    chdir: "{{ ansible_ssh_user_home }}"
        #  become_user: "{{ ansible_ssh_user }}"

    - name: npm安装相关工具
      command:
        cmd: "/usr/bin/npm install -g {{ item }}"
        chdir: "{{ ansible_ssh_user_home }}"
      environment:
        HTTP_PROXY: "{{ clash_proxy_url }}:{{ clash_proxy_port }}"
        HTTPS_PROXY: "{{ clash_proxy_url }}:{{ clash_proxy_port }}"
      loop:
        - "n@9.1.0"
        - "json@11.0.0"
        - "yarn@1.22.19"
        - "bash-language-server"
      #become_user: "{{ ansible_ssh_user }}"
      register: npm_install_result
      until: npm_install_result.failed == false
      retries: 3
      delay: 3

    - name: 使用n升级node # 这里执行升级后，很有可能导致npm报错，需要注意n的版本
      command:
        cmd: "/usr/local/bin/n 16.18.0" # n stable 或 n 14.14.0
        chdir: "{{ ansible_ssh_user_home }}"
      environment:
        HTTP_PROXY: "{{ clash_proxy_url }}:{{ clash_proxy_port }}"
        HTTPS_PROXY: "{{ clash_proxy_url }}:{{ clash_proxy_port }}"
      #become_user: "{{ ansible_ssh_user }}"
      register: n_update_result
      until: n_update_result.failed == false
      retries: 3
      delay: 3

    - name: 测试结果
      command:
        cmd: "npm ls -g"
        chdir: "{{ ansible_ssh_user_home }}"
      register: npm_ls_result

    - name: 输出测试结果
      debug: 
        msg: "{{ npm_ls_result.stdout_lines }}"
