---
- name: 部署script
  hosts: ubuntu_22
  become: yes
  vars:
    current_user: "{{ ansible_ssh_user | default(lookup('env', 'USER'), true) }}"
    current_pass: "{{ ansible_ssh_pass | default(lookup('env', 'USER'), true) }}"
    current_become_pass: "{{ ansible_become_pass | default(lookup('env', 'USER'), true) }}"
    current_user_home: "{{ ansible_ssh_user_home | default(lookup('env', 'HOME'), true) }}"
  any_errors_fatal: true
  tasks:
    - name: 删除残留的script
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /opt/script

    - name: 下载script
      include_tasks: util_git_clone_root.yml
      vars:
        git_repo_url: "https://github.com/gvls/script.git"
        git_repo_dir: "/opt/script"

    - name: 配置script
      blockinfile:
        path: "/etc/profile"
        block: |
          export PATH=$PATH:/opt/script/bin/
        marker: "# {mark} script BLOCK"
        create: yes

    # - name: 安装SCVPN
    #   ansible.builtin.copy:
    #     src: ./pkg/SCVPN
    #     dest: /opt/script/bin/SCVPN
    #     #owner: "{{ current_user }}"
    #     #group: "{{ current_user }}"
    #     mode: '0755'
    #   #become_user: "{{ current_user }}"

