---
- name: 部署shell
  hosts: ubuntu_22
  become: yes
  any_errors_fatal: true
  tasks:
    - name: 配置shell
      blockinfile:
        path: "{{ ansible_ssh_user_home }}/.bashrc"
        block: |
          alias mv='mv -i'
          alias cman='man -M /usr/share/man/zh_CN'
        marker: "# {mark} shell BLOCK"
        create: yes
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
      become_user: "{{ ansible_ssh_user }}"
