---
- name: 修改/opt/go/pkg目录权限
  ansible.builtin.file:
    path: /opt/go/pkg
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    recurse: yes

- name: go get {{ go_project }}
  command:
    cmd: "/usr/local/go/bin/go get {{ go_project }}"
    chdir: "/opt/go/src/example/"
  environment:
    GOPATH: "/opt/go"
    GOPROXY: "https://goproxy.cn,direct"
    HTTPS_PROXY: "{{ clash_proxy_url }}:{{ clash_proxy_port }}"
  become_user: "{{ ansible_ssh_user }}"
  register: command_result
  until: command_result.failed == false
  retries: 3
  delay: 3

- name: go install {{ go_project }}
  command:
    cmd: "/usr/local/go/bin/go install {{ go_project }}"
    chdir: "/opt/go/src/example/"
  environment:
    GOPATH: "/opt/go"
    GOPROXY: "https://goproxy.cn,direct"
    HTTPS_PROXY: "{{ clash_proxy_url }}:{{ clash_proxy_port }}"
  become_user: "{{ ansible_ssh_user }}"
  register: command_result
  until: command_result.failed == false
  retries: 3
  delay: 3

    #- name: 输出go install结果
    #  debug:
    #    msg: "{{ command_result }}"
