---
- name: 部署vim
  hosts: ubuntu_22
  become: yes
  any_errors_fatal: true
  tasks:
    - name: 添加9.0版本的vim仓库
      ansible.builtin.command:
        cmd: add-apt-repository ppa:jonathonf/vim -y
      environment:
        https_proxy: "{{ clash_proxy_url }}:{{ clash_proxy_port }}"
        http_proxy: "{{ clash_proxy_url }}:{{ clash_proxy_port }}"
      when: true

    - name: 卸载旧的vim
      apt:
        name:
          - vim
        state: absent

    - name: 删除残留的vim配置
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        # - "{{ ansible_ssh_user_home }}/.vim"
        - "/usr/local/vim"
      when: true

    - name: 更新软件源包列表
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: 安装vim
      apt:
        name:
          - vim # 8.2
          - ripgrep
          - shfmt
        state: present
      environment: # 9.0版本需要设置代理
        https_proxy: "{{ clash_proxy_url }}:{{ clash_proxy_port }}"
        http_proxy: "{{ clash_proxy_url }}:{{ clash_proxy_port }}"

    - name: 删除仓库 # 避免 apt update 失败
      ansible.builtin.command:
        cmd: add-apt-repository --remove ppa:jonathonf/vim -y
      environment:
        https_proxy: "{{ clash_proxy_url }}:{{ clash_proxy_port }}"
        http_proxy: "{{ clash_proxy_url }}:{{ clash_proxy_port }}"
      when: true

    - name: 下载vim配置
      include_tasks: util_git_clone_root.yml
      vars:
        git_repo_url: "https://github.com/gvls/vim.git"
        git_repo_dir: "/usr/local/vim"

    - name: 修改vim目录权限
      ansible.builtin.file:
        path: /usr/local/vim
        state: directory
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        recurse: yes

    - name: 链接vim配置到vim
      include_tasks: util_cat_append.yml
      vars:
        src_context: "/usr/local/vim/inject.txt"
        dst_file: "/etc/vim/vimrc"
        annotaion: '"'
        context_sign: "vim"

    # - name: 创建vim插件目录
    #   ansible.builtin.file:
    #     path: /usr/local/vim/plugged
    #     state: directory
    #     owner: "{{ ansible_ssh_user }}"
    #     group: "{{ ansible_ssh_user }}"

    # - name: 创建vim的coc数据目录
    #   ansible.builtin.file:
    #     path: /usr/local/vim/cocData
    #     state: directory
    #     owner: "{{ ansible_ssh_user }}"
    #     group: "{{ ansible_ssh_user }}"

    - name: 测试结果
      command:
        cmd: "/usr/bin/vim --version"
        chdir: "{{ ansible_ssh_user_home }}"
      register: vim_version_result

    - name: 输出测试结果
      debug: 
        msg: "{{ vim_version_result.stdout_lines }}"

    - name: 输出需要做的后续操作
      debug: 
        msg: |
          vim a.go
              # :PlugUpgrade
              :PlugInstall
              :GoInstallBinaries
          /usr/local/vim/myConfig.sh
          vim /usr/local/vim/vimConfig.vim
              let g:go_imports_autosave = 0
